# Generated by Django 5.0.6 on 2024-05-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('Latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('redTime', models.IntegerField()),
                ('redGreen', models.IntegerField()),
            ],
        ),
    ]
