# Generated by Django 5.0.6 on 2024-05-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_avenue_intersection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avenue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avenue',
            name='length_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avenue',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='intersection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lanegroup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
