# Generated by Django 5.0.6 on 2024-05-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_avenue_description_avenue_length_meters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intersection',
            name='latitude',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intersection',
            name='longitude',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
