# Generated by Django 5.0.6 on 2024-05-23 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_intersection_latitude_intersection_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avenue',
            old_name='length_meters',
            new_name='lengthMeters',
        ),
        migrations.RenameField(
            model_name='lanegroup',
            old_name='num_lanes',
            new_name='numLanes',
        ),
        migrations.RenameField(
            model_name='trafficlight',
            old_name='yellow_time',
            new_name='yellowTime',
        ),
    ]
