# Generated by Django 5.0.6 on 2024-05-24 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_alter_intersection_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intersection',
            name='location',
        ),
    ]
