# Generated by Django 5.0.6 on 2024-05-24 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_rename_intersection_lanegroup_intersectionid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lanegroup',
            old_name='intersectionId',
            new_name='intersections',
        ),
    ]
