# Generated by Django 5.0.6 on 2024-05-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_rename_intersectionid_lanegroup_intersections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lanegroup',
            old_name='intersections',
            new_name='intersection',
        ),
    ]
