# Generated by Django 5.0.6 on 2024-05-24 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_rename_intersections_lanegroup_intersection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lanegroup',
            name='intersection',
        ),
        migrations.RemoveField(
            model_name='trafficlight',
            name='lane_group',
        ),
        migrations.AddField(
            model_name='avenue',
            name='intersection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.intersection'),
        ),
    ]
