# Generated by Django 5.0.6 on 2024-05-24 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0012_remove_lanegroup_intersection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avenue',
            name='intersection',
        ),
        migrations.AddField(
            model_name='lanegroup',
            name='intersection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.intersection'),
        ),
    ]
