# Generated by Django 5.0.6 on 2024-05-26 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0013_remove_avenue_intersection_lanegroup_intersection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafficlight',
            old_name='redGreen',
            new_name='greenTime',
        ),
    ]
