# Generated by Django 5.0.6 on 2024-06-01 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0015_trafficlight_avenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlight',
            name='pressure_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='TrafficFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vehicle_count', models.IntegerField()),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.intersection')),
                ('lane_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.lanegroup')),
            ],
        ),
    ]
