# Generated by Django 5.0.6 on 2024-06-03 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0017_rename_lane_group_trafficflow_lanegroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficflow',
            name='intersection',
        ),
        migrations.AlterField(
            model_name='trafficflow',
            name='laneGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.lanegroup'),
        ),
    ]
