# Generated by Django 5.0.6 on 2024-05-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_role_alter_userprofile_user_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
